DEBUG_FLAG = $(if $(DEBUG),-debug)

deps:
	go get github.com/andrew-d/go-termutil/...
	go get github.com/codegangsta/cli/...
	go get github.com/mgutz/ansi/...
	go get -d -t ./...

test: deps
	go test -v ./...

install: deps
	go install
